POST  http://localhost:3003/api/pizzas
Content-Type: application/json

{
    "name": "Mussarela",
    "price": 40,
    "ingredients": "Massa, molho de tomate e queijo mussarela."
}

###

GET http://localhost:3003/api/pizzas

###

POST  http://localhost:3003/api/orders
Content-Type: application/json

{
    "pizza": "Gorgonzola",
    "quantity": 1
}

###

GET http://localhost:3003/api/orders

###

###

GET http://localhost:3003/api/orders/1

###